
version: '3.4'
services:

  nginx:
    stdin_open: true
    ports: 
      - 3000:80

  portainer:
    stdin_open: true

  redis:
    stdin_open: true
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-commander:
    environment:
      - REDIS_HOSTS=local:redis:6379
      - PORT=8083

  mongodb:
    stdin_open: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=nestauthmongo

  mongo-express:
    stdin_open: true
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_SITE_BASEURL=/__info__/mongo-express

  apiauth:
    build: 
      dockerfile: Dockerfile
    args:
      NODE_ENV: development
      # target: dev
    stdin_open: true
    volumes: 
      - /app/node_modules 
      - ../api:/app
    environment:
      - REDIS=redis
      - PORT=3000
      # to specify any other option for connection add ?retryWrites=true
      # to import data in mongo mongorestore --gzip --archive=sampledata.archive.gz
      - MONGOUSER=root
      - MONGOPASS=secret
      - DBURL=mongodb://<MONGOUSER>:<MONGOPASS>@mongodb:27017
      - DBNAME=nestauthmongo

      - NODE_ENV=development
      - CORS=http://localhost:3000

      - JWT_TTL=365d
      - JWT_KEY=uy6hw65hywtrnbewhnterwhg
      - RESET_TOKEN_EXP=600
      - SENDGRID_USER=nazemi.works@gmail.com
      - SENDGRID_PASS=https://signup.sendgrid.
      - EMAIL_FROM=security@devref.ir
      - SMTP_SERVER=fdsfdsfsdfsdfsdfsdf


# docker-compose run can run command shell 