
version: '3.4'
services:

  nginx:
    restart: always
    image: 'nginx:stable-alpine'
    tty: true
    depends_on: 
      - apiauth
      - redis
      - mongodb
      - redis-commander
      - mongo-express
      - portainer
    volumes: 
      # remember!!!!!!! add trust proxy to nodejs services
      - ../default.conf:/etc/nginx/conf.d/default.conf:ro #read only 

  portainer:
    image: portainer/portainer-ce
    restart: always
    volumes:
      - portainer_data_vol:/data
      - /var/run/docker.sock:/var/run/docker.sock 

  redis:
    image: "redis:7.0.0-alpine"
    restart: always
    volumes:
      - redis_vol:/var/lib/redis
  
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    restart: always
    depends_on: 
      - redis

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ../db/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_vol:/data/db

  mongo-express:
    image: mongo-express
    restart: always 
    depends_on:
      - mongodb

  apiauth:
    build: 
      context: ../api
      image: penkong/nestauthmongo
    restart: always
    environment:
      - PORT=3000
    depends_on:
      - mongodb
      - redis
  


volumes:
  mongo_vol:
    driver: local
  portainer_data_vol:
    driver: local
  redis_vol:
    driver: local